//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_staging
    {
        public int category_id { get; set; }
        public string category_name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> a { get; set; }
        public Nullable<int> b { get; set; }
        public Nullable<int> c { get; set; }
        public Nullable<int> d { get; set; }
        public Nullable<int> e { get; set; }
        public Nullable<int> f { get; set; }
        public Nullable<int> g { get; set; }
    }
}
