//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnualAvgByLane> AnnualAvgByLanes { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<CorridorDetector> CorridorDetectors { get; set; }
        public virtual DbSet<Corridor> Corridors { get; set; }
        public virtual DbSet<Errors2015> Errors2015 { get; set; }
        public virtual DbSet<Errors2016> Errors2016 { get; set; }
        public virtual DbSet<Errors2017> Errors2017 { get; set; }
        public virtual DbSet<Errors2018> Errors2018 { get; set; }
        public virtual DbSet<LaneErrors2015> LaneErrors2015 { get; set; }
        public virtual DbSet<LaneErrors2016> LaneErrors2016 { get; set; }
        public virtual DbSet<LaneErrors2017> LaneErrors2017 { get; set; }
        public virtual DbSet<LaneErrors2018> LaneErrors2018 { get; set; }
        public virtual DbSet<RawData2015> RawData2015 { get; set; }
        public virtual DbSet<RawData2016> RawData2016 { get; set; }
        public virtual DbSet<RawData2017> RawData2017 { get; set; }
        public virtual DbSet<RawData2018> RawData2018 { get; set; }
        public virtual DbSet<Validity> Validities { get; set; }
        public virtual DbSet<DetectorLane> DetectorLanes { get; set; }
        public virtual DbSet<vw_AvgHourlySpeed> vw_AvgHourlySpeed { get; set; }
        public virtual DbSet<vw_AvgHourlyThroughput> vw_AvgHourlyThroughput { get; set; }
        public virtual DbSet<vw_DetectorMiscData> vw_DetectorMiscData { get; set; }
        public virtual DbSet<vw_Errors> vw_Errors { get; set; }
        public virtual DbSet<vw_ExistingLanes> vw_ExistingLanes { get; set; }
        public virtual DbSet<vw_LaneErrors> vw_LaneErrors { get; set; }
        public virtual DbSet<vw_RawData> vw_RawData { get; set; }
        public virtual DbSet<vw_Validity> vw_Validity { get; set; }
        public virtual DbSet<Detector> Detectors { get; set; }
    }
}
