//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jacobs_PlayPenEntities : DbContext
    {
        public Jacobs_PlayPenEntities()
            : base("name=Jacobs_PlayPenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<CorridorDetector> CorridorDetectors { get; set; }
        public virtual DbSet<Corridor> Corridors { get; set; }
        public virtual DbSet<detector_AvgByLane> detector_AvgByLane { get; set; }
        public virtual DbSet<detector_AvgHourlySpeed> detector_AvgHourlySpeed { get; set; }
        public virtual DbSet<detector_AvgHourlyThroughput> detector_AvgHourlyThroughput { get; set; }
        public virtual DbSet<detector_MiscData> detector_MiscData { get; set; }
        public virtual DbSet<detector_Validity> detector_Validity { get; set; }
        public virtual DbSet<Detector> Detectors { get; set; }
        public virtual DbSet<vw_detector_AvgByLane> vw_detector_AvgByLane { get; set; }
        public virtual DbSet<vw_detector_AvgHourlySpeed> vw_detector_AvgHourlySpeed { get; set; }
        public virtual DbSet<vw_detector_AvgHourlyThroughput> vw_detector_AvgHourlyThroughput { get; set; }
        public virtual DbSet<vw_detector_MiscData> vw_detector_MiscData { get; set; }
        public virtual DbSet<vw_detector_Validity> vw_detector_Validity { get; set; }
        public virtual DbSet<vw_Errors> vw_Errors { get; set; }
        public virtual DbSet<vw_ExistingLanes> vw_ExistingLanes { get; set; }
        public virtual DbSet<vw_LaneErrors> vw_LaneErrors { get; set; }
        public virtual DbSet<vw_RawData> vw_RawData { get; set; }
    }
}
