//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllDetectors2018> AllDetectors2018 { get; set; }
        public virtual DbSet<AllTheData> AllTheDatas { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<category_staging> category_staging { get; set; }
        public virtual DbSet<Detector> Detectors { get; set; }
        public virtual DbSet<Errors2018> Errors2018 { get; set; }
        public virtual DbSet<LaneErrors2018> LaneErrors2018 { get; set; }
        public virtual DbSet<RawData2017> RawData2017 { get; set; }
        public virtual DbSet<RowCompare> RowCompares { get; set; }
        public virtual DbSet<updatedProcess_test1> updatedProcess_test1 { get; set; }
        public virtual DbSet<AvgHourlySpeed2018> AvgHourlySpeed2018 { get; set; }
        public virtual DbSet<AvgHourlyThroughput2018> AvgHourlyThroughput2018 { get; set; }
        public virtual DbSet<DetectorLane> DetectorLanes { get; set; }
        public virtual DbSet<vw_AvgHourlySpeed2018> vw_AvgHourlySpeed2018 { get; set; }
        public virtual DbSet<vw_AvgHourlyThroughput2018> vw_AvgHourlyThroughput2018 { get; set; }
    }
}
