//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaneErrors2018
    {
        public int id { get; set; }
        public Nullable<int> detector_number { get; set; }
        public Nullable<System.DateTime> collected { get; set; }
        public Nullable<short> min_since { get; set; }
        public Nullable<int> lane1 { get; set; }
        public Nullable<int> lane2 { get; set; }
        public Nullable<int> lane3 { get; set; }
        public Nullable<int> lane4 { get; set; }
        public Nullable<int> lane5 { get; set; }
        public Nullable<int> lane6 { get; set; }
        public Nullable<int> lane7 { get; set; }
        public Nullable<int> lane8 { get; set; }
        public Nullable<int> lane9 { get; set; }
        public Nullable<int> lane10 { get; set; }
        public Nullable<int> HOV { get; set; }
        public Nullable<int> HOV2 { get; set; }
    }
}
