//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validity
    {
        public long id { get; set; }
        public Nullable<short> detector_number { get; set; }
        public int year { get; set; }
        public Nullable<int> error { get; set; }
        public Nullable<int> valid { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> pct { get; set; }
    }
}
