//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Errors
    {
        public int year { get; set; }
        public int id { get; set; }
        public Nullable<int> detector_number { get; set; }
        public Nullable<System.DateTime> collected { get; set; }
        public Nullable<short> min_since { get; set; }
        public Nullable<bool> speed_error { get; set; }
        public Nullable<bool> volume_error { get; set; }
        public Nullable<bool> occupancy_error { get; set; }
        public Nullable<bool> difference_error { get; set; }
        public Nullable<bool> zeros_error { get; set; }
    }
}
