//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedReport
    {
        public System.Guid id { get; set; }
        public Nullable<int> det_num { get; set; }
        public Nullable<int> corridor_id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool completed { get; set; }
        public System.DateTime date_submitted { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public string email { get; set; }
    }
}
