//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_detector_MiscData
    {
        public Nullable<System.Guid> Id { get; set; }
        public Nullable<short> detector_number { get; set; }
        public Nullable<int> num_days { get; set; }
        public Nullable<int> gp_lane_cnt { get; set; }
        public Nullable<int> hov_lane_cnt { get; set; }
        public int year { get; set; }
    }
}
